networks:
  bazy_danych_network:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - bazy_danych_network
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      POSTGRES_NAME: bazaDanych
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      JWT_SECRET_KEY: secret_jwt_key

  db:
    networks:
      - bazy_danych_network
    image: postgres:alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_DB: bazaDanych
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/backup.dump:/docker-entrypoint-initdb.d/backup.dump
    command: >
      sh -c "docker-entrypoint.sh postgres && pg_restore -U $${POSTGRES_USER} -d $${POSTGRES_DB} /docker-entrypoint-initdb.d/backup.dump"

volumes:
  pgdata:
