"""first migration

Revision ID: 517303222a12
Revises: 
Create Date: 2024-12-28 16:29:33.910862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517303222a12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('kcal', sa.SmallInteger(), nullable=True),
    sa.Column('protein', sa.SmallInteger(), nullable=True),
    sa.Column('carbs', sa.SmallInteger(), nullable=True),
    sa.Column('fat', sa.SmallInteger(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['link_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('diet_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['meal_category.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['diet_id'], ['diet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_details',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('kcal_goal', sa.SmallInteger(), nullable=True),
    sa.Column('fat_goal', sa.SmallInteger(), nullable=True),
    sa.Column('protein_goal', sa.SmallInteger(), nullable=True),
    sa.Column('carb_goal', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_diets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('diet_id', sa.Integer(), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['diet_id'], ['diet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local_meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composition', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('meal_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_meal_id', sa.Integer(), nullable=True),
    sa.Column('portion', sa.Float(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['local_meal_id'], ['local_meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_meal_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['local_meal_id'], ['local_meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_schedule')
    op.drop_table('food_log')
    op.drop_table('meal_ingredients')
    op.drop_table('local_meals')
    op.drop_table('user_diets')
    op.drop_table('user_details')
    op.drop_table('meal')
    op.drop_table('links')
    op.drop_table('user')
    op.drop_table('meal_category')
    op.drop_table('link_types')
    op.drop_table('ingredients')
    op.drop_table('diet')
    # ### end Alembic commands ###
