"""Initial migration.

Revision ID: 6f7acc3212d3
Revises: 517303222a12
Create Date: 2025-01-18 13:15:29.242364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f7acc3212d3'
down_revision = '517303222a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('generic_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('kcal_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('protein_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('labels_tags', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('product_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('allergens', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tsv', postgresql.TSVECTOR(), nullable=True))
        batch_op.create_index('tsv_idx', ['tsv'], unique=False, postgresql_using='gin')
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('carbs')
        batch_op.drop_column('kcal')
        batch_op.drop_column('fat')
        batch_op.drop_column('protein')
        batch_op.drop_column('description')

    with op.batch_alter_table('meal_ingredients', schema=None) as batch_op:
        batch_op.create_unique_constraint('_meal_ingredient_uc', ['meal_id', 'ingredient_id'])

    with op.batch_alter_table('user_diets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('diet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('_user_diet_uc', ['user_id', 'diet_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_diets', schema=None) as batch_op:
        batch_op.drop_constraint('_user_diet_uc', type_='unique')
        batch_op.alter_column('diet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('meal_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('_meal_ingredient_uc', type_='unique')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('protein', sa.SMALLINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fat', sa.SMALLINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kcal', sa.SMALLINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.SMALLINT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('tsv_idx', postgresql_using='gin')
        batch_op.drop_column('tsv')
        batch_op.drop_column('allergens')
        batch_op.drop_column('product_quantity')
        batch_op.drop_column('labels_tags')
        batch_op.drop_column('image_url')
        batch_op.drop_column('fat_100g')
        batch_op.drop_column('carbs_100g')
        batch_op.drop_column('protein_100g')
        batch_op.drop_column('kcal_100g')
        batch_op.drop_column('generic_name')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
